### ISSUE TITLE
how to use annotation on sense studio?

### ISSUE THREAD

**Issue by thunder95** [TwentyBN/sense#131]
There are splitted video frames on website of sense video.

Any guidelines or tutoral for that?

Background is supposed to be no action clip.
whats the difference about category_tag1, category_tag2.  Both of them distinguish the start and end of each action?

**Comment by corneliusboehm** [comment]
Except for this [Wiki Page](https://github.com/TwentyBN/sense/wiki/Tools) we don't have much documentation on the annotation tool yet, because we're still changing a lot there, sorry.

The general idea is that you can tag up to two specific events in your videos, which would be your `category_tag1` and `category_tag2`. For example when doing squats, you could annotate the low/sitting and the high/standing position. This would enable the model to detect those and even count how many squats you are doing by checking how often you alternate between those two positions.

**Comment by thunder95** [comment]
ok,  jetzt mir is alles klar.  thank you!
