### ISSUE TITLE
Need Help!!  When I run normally, I am always prompted 'no module named' futures'

### ISSUE THREAD

**Issue by 444340687** [TwentyBN/sense#169]
Halloechen~~~, many thanks for this great project in Advance.
When I run normally, I always report errors‘no module named' futures’.But I have normal pip, please help me solve this problem

**Comment by corneliusboehm** [comment]
Hey there, I'm glad to hear you like our project!
Can you quickly confirm to me, which versions of python and pip you are using for your setup? This project has been developed on python 3.6. Maybe you also need to do `pip3 install -r requirements.txt` to use the correct version of pip.

**Comment by Feliciacedele** [comment]
Hi, I've also came up with the problem of ‘no module named' futures’.
I'm using python 3.8, then i used pip3 for re-setup but the same error reports popped up.

**Comment by loreckc** [comment]
Thanks again for the repo, I am running into the same issue. Tested both locally and in an Colab environment. Any news about this? 

`Traceback (most recent call last):
  File "tools/sense_studio/sense_studio.py", line 22, in <module>
    from sense import SPLITS
  File "/usr/local/lib/python3.7/dist-packages/sense.py", line 13, in <module>
    import futures
ModuleNotFoundError: No module named 'futures'`

**Comment by YasheshSavani** [comment]
Thank you @loreckc for reporting the issue. I am not able to generate this issue but I might have two solutions if you can give them a quick try and let me know if any works:

Solution: 
- Try uninstalling futures first by `pip3 uninstall future`
- Then try running `pip3 install -r requirements,txt`. 
 
if the above solution does not help you, try running the below commands:
`python3 -m pip install -r requirements.txt` or  `python3 -m pip install future` for a specific package.

**Comment by loreckc** [comment]
Hey @YasheshSavani , thanks for your reply and your help. It still does not run, tried both solutions and even tried to reinstall pip / pip3, tried several Python Versions and stuff like that. Actually I have no further idea, but it definitely seems to be a Python environment problem. I will keep you guys updated if I find any fix, the repo itself seems to be pretty cool.

**Comment by loreckc** [comment]
Alright, as we already expected it's an issue regarding the Python environment. 

There seems to be problems if on the machine are several Python/Conda envs Installed, including a Python-Module that is also called "sense". Even using PYTHONPATH=./ seems to don't help inside the Conda environment, so that the machine is running the wrong Python sense-package instead of running the correct script. On MacOS it helped to uninstall all the several Python Packages including the misleading "sense"-package, reinstall Conda and then proceed as described in the repository by creating a new Conda environment, activate it and run `pip install -r requirements.txt`. 
Again don't forget to use 'PYTHONPATH=./' as argument before running the examples. 

I think this issue can be closed since its based on messed up python environments like mine and not on lack of code quality of the repository. ;-)

**Comment by YasheshSavani** [comment]
Thank you @loreckc for clearing out the issue :+1:
