### ISSUE TITLE
why are my fps rates so low

### ISSUE THREAD

**Issue by NB-Xie** [TwentyBN/sense#175]
Thank you for your amazing work!

I was trying to run the examples/ run_gesture_recognition.py , with cpu (i5-8400 CPU @ 2.80GHz) on win10
I thought it would be a real- time recognizer but the camera / model fps seemed to be very low:
around **13 / 1.2 fps**   for efficientnet 
and around **14 / 3.5 fps** for mobilenetv2.

I don't know if it is normal, 
do you have any suggestions ? 
![image](https://user-images.githubusercontent.com/84755813/119430838-0d177900-bd44-11eb-8533-80dbe39a1e73.png)
![image](https://user-images.githubusercontent.com/84755813/119430952-42bc6200-bd44-11eb-8947-d7b5750260d1.png)

**Comment by NB-Xie** [comment]
My running of run_gesture_detection.py  had the same issue

**Comment by corneliusboehm** [comment]
Hey @NB-Xie, thanks a lot for checking out our project!

The framerates you observe for mobilenet are actually very close to the target values. In the optimal case it would be running at 16fps camera input and 4 fps model output. This is specifically configured so that the models can be executed in real-time on different hardware. In our applications, the 4 predictions per second were usually frequent enough.

Efficientnet is a little more complex, so you might need a GPU to run it at the desired speed.

Thanks a lot for raising this issue again. We will try to clarify again in the README that 16 / 4fps **is** the expected real-time behavior.

**Comment by NB-Xie** [comment]
Thank you!

**Comment by MoonBunnyZZZ** [comment]
> Thank you for your amazing work!
> 
> I was trying to run the examples/ run_gesture_recognition.py , with cpu (i5-8400 CPU @ 2.80GHz) on win10 I thought it would be a real- time recognizer but the camera / model fps seemed to be very low: around **13 / 1.2 fps** for efficientnet and around **14 / 3.5 fps** for mobilenetv2.
> 
> I don't know if it is normal, do you have any suggestions ? ![image](https://user-images.githubusercontent.com/84755813/119430838-0d177900-bd44-11eb-8533-80dbe39a1e73.png) ![image](https://user-images.githubusercontent.com/84755813/119430952-42bc6200-bd44-11eb-8947-d7b5750260d1.png)

Hi, do you have tje downloaded models? @NB-Xie
